Feature enhance start stop scripts
pravega/flink-tools pull request #19
Opened 2021-06-18 17:39 UTC by kvandra

Added two delete scripts to provide automation for these tasks
Removed set -ex from scripts to minimize output
updated publish to check the status of gradlew publish command
enhanced start-job,sh to check different stages for creating the flink application - i.e. FlinkCluster created, FlinkApplication is deployed and checkpoint completed

tested with both data generator and stream-to-stream

2021-06-22 04:54 UTC, claudiofahey requested changes

2021-06-22 04:54 UTC, claudiofahey commented on scripts/delete-job.sh
> +### set -ex
Remove this commented command.

2021-06-22 04:54 UTC, claudiofahey commented on scripts/delete-pravega-stream.sh
> +###ret_policy_type=d
Remove commented commands.

2021-06-22 04:54 UTC, claudiofahey commented on scripts/delete-pravega-stream.sh
> +stream_name="sensor-stream"
It is not safe to have a default stream name to delete. This should be a required argument.

2021-06-22 04:54 UTC, claudiofahey commented on scripts/publish.sh
> +### set -ex
`set -ex` sets two options. `-x` prints every command before executing this. This is very useful for troubleshooting but I'm ok with removing it. `-e` causes the script to abort if any command exits with an error. This needs to stay. So change this to `set -e`.

2021-06-22 04:54 UTC, claudiofahey commented on scripts/publish.sh
> +    echo "STATUS $?"
No need to check for errors if you keep `set -e`.

2021-06-22 04:54 UTC, claudiofahey commented on scripts/start-job.sh
> +    state=$(kubectl get FlinkCluster -n ${NAMESPACE} ${RELEASE_NAME} | grep ${RELEASE_NAME} | awk '{print $7}')
Very nice!

2021-06-22 04:54 UTC, claudiofahey commented on scripts/start-job.sh
> +done
You should add `sleep 1s` here so that it doesn't call kubectl too often.

2021-07-15 21:13 UTC, kvandra commented on scripts/delete-pravega-stream.sh
> +###ret_policy_type=d
removed comment

2021-07-15 21:14 UTC, kvandra commented on scripts/delete-pravega-stream.sh
> +stream_name="sensor-stream"
Made both scope and stream_name blank and added a test if either item is not specified on the command line

2021-07-15 21:14 UTC, kvandra commented on scripts/publish.sh
> +### set -ex
Changed to set -e

2021-07-15 21:15 UTC, kvandra commented on scripts/publish.sh
> +    echo "STATUS $?"
removed the echo statement

2021-07-15 21:15 UTC, kvandra commented on scripts/start-job.sh
> +    state=$(kubectl get FlinkCluster -n ${NAMESPACE} ${RELEASE_NAME} | grep ${RELEASE_NAME} | awk '{print $7}')
Thanks !!

2021-07-15 21:15 UTC, kvandra commented on scripts/start-job.sh
> +done
added sleep 5s since it takes minutes for operation to complete

2021-07-17 04:25 UTC, claudiofahey approved these changes
Thanks for the PR!

2021-07-17 04:28 UTC, merged